### ISSUE TITLE
Problems on rendering

### ISSUE THREAD

**Issue by xjchao7** [namjohn10/GenerativeGaitNet#2]
Thank you for your work. When I rendered the result,  I met the problems as following:
![eadb480c-2838-483b-b18e-8d81621effcb](https://user-images.githubusercontent.com/105781839/194746408-2632e4d5-c153-4027-bcda-8f31eb7be4b4.jpg)
Do you know how to deal with it?

**Comment by Xianjin111** [comment]
I have dealt with it by changing the version of ray. Thank you.
